### ISSUE TITLE
[Feature request] CheckRedirect hook.

### ISSUE THREAD

**Issue by sagan** [Noooste/azuretls-client#101]
The current behavior of azuretls-client's redirect following does not preserve the request scope OrderedHeaders of the original request. To persist headers across redirections, one has to use the session scope OrderedHeaders, which is not ideal in some circumstances (For example, I am setting the Cookie headers and I don't use azuretls's built in cookie jar by always setting req.NoCookie flag).

I suggest adding a new CheckRedirect hook, similar to go standard http client's [CheckRedirect](https://pkg.go.dev/net/http#Client.CheckRedirect). It will allow user gain more control of the redirection, like setting headers or other parameters of the new request, or even prevent the redirection. it may looks like:

```go
func CheckRedirect(req *Request, reqs []*Request) error
```

It could be a session scope or request scope hook, or both.

**Comment by Noooste** [comment]
Hi, thanks for pointing that out, I think it's a good feature that needs to be implemented.
