### ISSUE TITLE
Index out of range in profiles.go

### ISSUE THREAD

**Issue by byMonaco** [Noooste/azuretls-client#102]
![IMG_8712](https://github.com/Noooste/azuretls-client/assets/60541017/174aff6a-ca97-4cab-ad3a-9ef16a835b26)

**Comment by Noooste** [comment]
Thank you for reporting this problem. Is there any way to reproduce this behavior?

**Comment by byMonaco** [comment]
> Thank you for reporting this problem. Is there any way to reproduce this behavior?

I just using session.GetClientHelloSpec = azuretls.GetLastChromeVersion

And 1-2 from 1kk requests get this error. I think it randomly. Maybe problem in rdn.Shuffle method in profiles.go (line 70)
