### ISSUE TITLE
HTTP2 pseudo-header order and other issues.

### ISSUE THREAD

**Issue by VegieIsCute** [Noooste/azuretls-client#114]
**Describe the bug**
A few inconsistencies are present in the HTTP2 packet:

First, :path and is misplaced. Well this is partly true, the current configuration is used by chromium based browsers, however, firefox does things a bit differently, and id assume other browser do the same as well. Adding a feature to adjust the order of the pseudo-headers would be great.

Second, is the WINDOW_UPDATE frame and priority frame in the http2 packet, this i believe is more closely related to the other issue i opened where the HTTP2 string wasn't being parsed properly.

**To Reproduce**
Make requests to 
https://tls.peet.ws/api/all

**Expected behavior**
HTTP2 should be applied correctly, and psuedo header order should be a feature.

**Screenshots**
![image](https://github.com/user-attachments/assets/58bb5835-a492-4cf8-99dc-afc580168a34)
![image](https://github.com/user-attachments/assets/36293d13-1c8f-4312-a857-6c7c67ec10af)
![image](https://github.com/user-attachments/assets/aa22f02e-645f-4d45-80b2-7a2239a8d844)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 128

**Comment by VegieIsCute** [comment]
The http2 fingerprint is: 1:65536,4:131072,5:16384|12517377|3:0:0:201,5:0:0:101,7:0:0:1,9:0:7:1,11:0:3:1,13:0:0:241|m,p,a,s, it doesn't get set properly.

**Comment by VegieIsCute** [comment]
Ok to confirm, I'm not sure what was going on, it seems the issue isn't present anymore and the http2 fingerprint is now different? It may have been something with my fiddler client not sure. The parsing issue doesn't seem to exist anymore so please ignore that issue, pseudo-header is also fine now.

Apologies on my end, however another issue is still present.

The end of the http2 packet, the last priorities object seems to be copied from chrome. However this doesn't fit firefox.

Firefox:
![image](https://github.com/user-attachments/assets/b3d25e6b-fc7c-4ba5-8864-94e7c19c2814)


Azuretls:
![image](https://github.com/user-attachments/assets/2244deb5-b9ad-44ef-8a85-afca4220c346)

Chrome: 
![image](https://github.com/user-attachments/assets/520c92fb-2836-422b-ba3f-89f6b34a4a62)

**Comment by VegieIsCute** [comment]
Any updates regarding this issue?

**Comment by Noooste** [comment]
Hello,
Firefox is already set in HTTP/2 presets, use `session.Browser = azuretls.Firefox` to have the correct specs
