### ISSUE TITLE
CONNECT requests fail under proxy connections.

### ISSUE THREAD

**Issue by VegieIsCute** [Noooste/azuretls-client#115]
**Describe the bug**
When a proxy is applied, and a connect request is made, the request fails with the error "proxy connection timeout" immediately.

**To Reproduce**
```
session := azuretls.NewSession()
defer session.Close()
_ = session.SetProxy("YOUR PROXY")
err := session.Connect("http://tls.peet.ws:443")
if err != nil {
    fmt.Println(err)
}
```

**Expected behavior**
CONNECT requests to succeed even under proxies.

**Screenshots**
![image](https://github.com/user-attachments/assets/ab36d7d6-3947-434d-8e83-793a823adbee)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 128

**Comment by Noooste** [comment]
Thanks for reporting me this, will be patched asap!
