### ISSUE TITLE
tunnel does not use set headers.

### ISSUE THREAD

**Issue by VegieIsCute** [Noooste/azuretls-client#116]
**Describe the bug**
When a request is made from azuretls, it will first "CONNECT" to the server. I opened a previous issue where the connect request failed under proxy. During this i couldn't debug the request but it seems that if a connection isn't made, azure will automatically perform a connect request on its own. 

The problem is the headers. header order, header punctuation, and header values. azuretls doesn't seem to follow the defined headers for it when connecting. After checking fiddler, the connect request was using a Chrome 126 user agent, captial cased headers, and improper header order.

Just for some info, firefox's CONNECT request looks like this.
![image](https://github.com/user-attachments/assets/9435a400-a85e-496c-a080-2af94ae5944b)

While azuretls, even with the useragent header being set to firefox, looks like this.
![image](https://github.com/user-attachments/assets/46debec6-c740-430a-af82-b46229566d54)

It seems that firefox has 2 "connection" headers, and a different order than chrome. I am requesting functionality to configure headers (including duplicate headers)

**To Reproduce**
perform a get request to any website, set proxy to fiddler local address, observe the tunnel request.

**Screenshots**
![image](https://github.com/user-attachments/assets/899e8ef8-8bd6-4c47-9e4f-46a07a4fdf0c)
![image](https://github.com/user-attachments/assets/e1e8a9f6-cfb8-4314-8e4e-d97b8faead4b)
![image](https://github.com/user-attachments/assets/dc3f4ebe-7c68-437b-afb7-62b92dc6fe83)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 128

**Comment by VegieIsCute** [comment]
Any updates?

**Comment by Noooste** [comment]
Hello,
Sorry, I am unable to resolve this issue at this time.
Any PR would be greatly appreciated.

**Comment by Noooste** [comment]
Hello,
I've pushed a new version, please now use `session.ProxyHeader` to set your customized proxy headers.
