### ISSUE TITLE
Why can't ja3 be set after setting up a proxy

### ISSUE THREAD

**Issue by WFWFDSF24** [Noooste/azuretls-client#127]
Why can't ja3 be set after setting up a proxy

      session := azuretls.NewSession()
	session.SetProxy("http://127.0.0.1:33210")
	session.InsecureSkipVerify = true
	t := time.Now()
	// First way
	ja3 := "771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-47-53,45-13-43-0-16-65281-51-18-11-27-35-23-10-5-17513-21-41,29-23-24,0"
	ja3 = "772,4867-49196-49244-49286-49287-49329-52393-52396-53249-53250-4868-4869-49199-49200-49248-49249-49290-49291-49324-49325-49326-49327-49330-49331-52392-53251-53253-16-56-106-107-49236-49240-49255-49273,65281-65037-35-45-0-5-13-11-23-43-51-16-27-10-17513-18,25497-29-23-24-14,0"
	ja3 = "772,4865-4867-49195-49196-49244-49245-49286-49287-49328-49329-52393-52396-53249-53250-4868-4869-49199-49200-49248-49290-49291-49324-49325-49326-49327-49330-49331-52392-53253-51-61-64-165-193-49212-49310-30-181-184-49174-49413,16-35-10-13-51-43-11-27-18-65281-23-5-0-17513-45-65037,29-23-24-9,0"
	if err := session.ApplyJa3(ja3, ""); err != nil {
		panic(err)
	}
	http2 := "1:65536,2:0,3:1000,4:6291456,6:262144|15663105|0|m,s,a,p"
	// var default_tls = *TlsSpecifications
	// default_tls = DefaultTlsSpecifications("")

	if err := session.ApplyHTTP2(http2); err != nil {
		panic(err)
	}

**Comment by Noooste** [comment]
Hello, 
I tried the code provided on my side and did not encounter any problem,
Do you still have this type of problem?
