### ISSUE TITLE
Adding support for Compressed Certificates during handshake

### ISSUE THREAD

**Issue by plasmarebel** [Noooste/azuretls-client#13]
Some CF sites use compressed certificates, when the client encounters such sites it throws the error "tls: received unexpected handshake message of type *tls.compressedCertificateMsg when waiting for *tls.certificateMsgTLS13"

CF uses brotli to compress certificates, being able use brotli for the certificates should fix this.

**Comment by Noooste** [comment]
Hello,
Can you provide me the url so I can test on my  side, brotli compression should be handled.

**Comment by plasmarebel** [comment]
> Hello, Can you provide me the url so I can test on my side, brotli compression should be handled.

https://www.footshop.com/

**Comment by Noooste** [comment]
Are you sure you're using the latest version of azuretls-client (v1.2.2)? I have no problem making requests to this endpoint.
