### ISSUE TITLE
Invalid extension : 65037 | boringssl support

### ISSUE THREAD

**Issue by Sysys242** [Noooste/azuretls-client#16]
**Describe the bug**
panic: invalid extension : 65037

**To Reproduce**
Just use this ja3: 771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,13-0-17513-11-16-23-27-5-35-51-10-65281-18-43-65037-45,29-23-24,0

**Expected behavior**
Support extensionEncryptedClientHello (boringssl) (65037) because it's used in tls client and to mimic browser it could be usefull

**Screenshots**
![image](https://github.com/Noooste/azuretls-client/assets/86845555/1b928ce4-5749-456d-9832-791e21888ae3)
![image](https://github.com/Noooste/azuretls-client/assets/86845555/30fe8681-ab58-4b26-9f3d-fcc7f1777120)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 119 | lastest of azuretls

**Comment by Noooste** [comment]
Hello, thanks for the report, it will be supported asap !
