### ISSUE TITLE
[Feature request] Prevent infinite redirecting

### ISSUE THREAD

**Issue by sagan** [Noooste/azuretls-client#20]
Some sites could behavior incorrectly by sending 301 / 302 redirection infinitely, always redirecting to the same url.

AzureTLS Client does not handle this circumstance well, and will lead the request to wait infinitely.

The Go standard http library limits redirection following to at most 10 times. I think there AzureTLS should provide a similar "MaxRedirections" setting in session and / or request.

**Comment by Noooste** [comment]
Hello, thank you for reporting this problem, I'll take these changes into account for the next update!
