### ISSUE TITLE
recaptcha.net not working

### ISSUE THREAD

**Issue by none21323** [Noooste/azuretls-client#26]
`
	session := azuretls.NewSession()
	session.OrderedHeaders = azuretls.OrderedHeaders{
		{"Host", "www.recaptcha.net"},
		{"Cookie", "_GRECAPTCHA=09APYnBZW-l9Y2FzQhqckkz48sV0KCb168F2Ui2C7RQDdp0bVHBXasvr3JApm1UhSZ2bedJK_HSJDiLTcS5FdEvOw"},
		//{"Content-Length", "7474"},
		{"Sec-Ch-Ua", "\"Chromium\";v=\"117\", \"Not;A=Brand\";v=\"8\""},
		{"Sec-Ch-Ua-Platform", "\"Linux\""},
		{"Sec-Ch-Ua-Mobile", "?0"},
		{"User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.5938.63 Safari/537.36"},
		{"Content-Type", "application/x-protobuffer"},
		{"Accept", "*/*"},
		{"Origin", "https://www.recaptcha.net"},
		{"Sec-Fetch-Site", "same-origin"},
		{"Sec-Fetch-Mode", "cors"},
		{"Sec-Fetch-Dest", "empty"},
		{"Referer", "https://www.recaptcha.net/recaptcha/enterprise/anchor?ar=1&k=6LdCCOUUAAAAAHTE-Snr6hi4HJGtJk_d1_ce-gWB&co=aHR0cHM6Ly93d3cucGF5cGFsb2JqZWN0cy5jb206NDQz&hl=en&v=u-xcq3POCWFlCr3x8_IPxgPu&size=invisible&cb=soqfo3xatqan"},
		{"Accept-Encoding", "gzip, deflate, br"},
		{"Accept-Language", "en-US;q=0.8,en;q=0.7"},
		{"Connection", "close"},
	}

	fileContent, err := ioutil.ReadFile("r.txt") //bytes 
	if err != nil {
		panic(err)
	}
	response, err := session.Post("https://www.recaptcha.net/recaptcha/enterprise/reload?k=6LdCCOUUAAAAAHTE-Snr6hi4HJGtJk_d1_ce-gWB", fileContent)

	if err != nil {
		panic(err)
	}
	fmt.Println(response.StatusCode, response.Body)
	defer session.Close()
`
	
	
	When I try to query the burp suite the response is returned as it should be something like this

)]}'
[ "rresp", "03AFcWeA7V7V7xcU_V0UJc66FX9jAZUuuCt-k4KsEYiHbs8PBlaxWgZ8VoS4aUVuueYxcOhjAT8mvKJv7fHECnQyn_-cecKgMbZ72CNjLsFcWaKs4fOyQcPlZA4AuCRQmVIkgMt6xA7lVzOTwI5QV244aSW0PC9- 6TnIny5n7X9cst831w20rUt7o0O0XkXJk7sWkONxHhYpiXXWjcstm8P3A2FjXxe_NNoTemUwEixOrvLSPGAprqqZCZ81InCf2inFIpieqqIVvCDzza1qfDpTyOKIbqDtc04. .......
(i.e. some debugging information for further work of the recaptcha script), but when I make a request through azuretls-client 
I get an almost empty response

go run azure_proxy.go 
200 [41 93 125 39 10 91 34 114 114 101 115 112 34 44 110 117 108 108 44 110 117 108 108 44 110 117 108 108 44 110 117 108 108 44 110 117 108 108 44 49 93]
go run azure_proxy.go 
200 )]}'
["rresp",null,null,null,null,null,null,1]
If translated into a string.
I think it's related to http2

**Comment by Noooste** [comment]
Hello, it's a bit complicated to help you. Have you tried using a middleman (such as Charles or Burp Suite) to see what is sent by the request? You can also activate the verbose function to get the query logs in your folder.
