### ISSUE TITLE
Though I have set the ip proxy and the response shows it worked, I found in the wireshark there is still first Client Hello with the website and the second with ip server

### ISSUE THREAD

**Issue by QinJun-1998** [Noooste/azuretls-client#274]
![image](https://github.com/user-attachments/assets/be9b3663-21cb-45b8-8cda-0a2ffbf18144)

As the scrrenshot shows, when I send a request with proxy set, it comes with two Client Hello in wireshark, the first shows the destination which belongs to the website I want to request, and the second belongs to my proxy

The proxy works fine as the response shows the request ip was my proxy.

I tried browser and other python library, when set with proxy it comes just proxy Client Hello.

could you help to check? many thanks

the simplest test code are:

session := azuretls.NewSession()
session.SetProxy("http://****:**")
r, _ := session.Get("https://tls.peet.ws/api/all")

**Comment by Noooste** [comment]
Hello,
The first connection is made for the built-in SSL pinning system, it connects to the server to get the server certificates to compare with the proxy connection.

If you trust your proxy enough, you can avoid this verification by using `session.InsecureSkipVerify = true`.

**Comment by QinJun-1998** [comment]
it works, thanks for you help :)
