### ISSUE TITLE
reset err CANCEL StreamID: 5

### ISSUE THREAD

**Issue by byMonaco** [Noooste/azuretls-client#32]
Hi! Thx for this package. It’s very good, but in multi threads console spam with messages and I think goroutine is lock after that, bc method no return.

"reset err CANCEL StreamID: 5"
"reset err CANCEL StreamID: 1"
"reset err CANCEL StreamID: 2"

```     
        session := azuretls.NewSession()
	defer session.Close()

	session.SetTimeout(25 * time.Second)
	session.GetClientHelloSpec = azuretls.GetLastChromeVersion
	session.UserAgent = data.GetUA()

        headers := azuretls.OrderedHeaders{
		{"Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"},
		{"Accept-Language", "en"},
	}

	_, err = session.Get("https://www.example.com/", headers)

	if err != nil {
		return false
	}

        return true

```

**Comment by Noooste** [comment]
In HTTP/2, each connection between a client and server can handle multiple requests at once through "streams." There's a limit on the number of concurrent streams a connection can have, effectively capping the number of simultaneous requests. To send more requests than this limit allows, you can use multiple sessions (therefore other HTTP/2 connections), distributing the requests across these connections to avoid hitting the limit on any single one.

**Comment by byMonaco** [comment]
> The issue is related to HTTP/2 connections.
> 
> In HTTP/2, each connection between a client and server can handle multiple requests at once through "streams." There's a limit on the number of concurrent streams a connection can have, effectively capping the number of simultaneous requests.
> 
> To send more requests than this limit allows, you can use multiple sessions (therefore other HTTP/2 connections), distributing the requests across these connections to avoid hitting the limit on any single one.

But i am using new session for new goroutine

**Comment by Noooste** [comment]
However, I've encountered the same problem for a single request from a session, so it's possible that your problem is due to the client. I'll look into it.

**Comment by byMonaco** [comment]
> However, I've encountered the same problem for a single request from a session, so it's possible that your problem is due to the client. I'll look into it.

Thank you!
