### ISSUE TITLE
Some goruitines is lock in session

### ISSUE THREAD

**Issue by byMonaco** [Noooste/azuretls-client#35]
Thanks for the latest update, but there is another bug in it. I think this was the case in the previous version too.

If i using proxy some goroutines is locked and no return, but without proxy all good. I think it's proxy problem.

Example code WITH PROXY: 
This code send GET request to site in 200 goroutines and need to always return if request complete.
After return it write in console how much returns was done.

```
import (
	"fmt"
	"strings"
	"sync"
	"time"

	"github.com/Noooste/azuretls-client"
)

var mutex = &sync.Mutex{}
var TotalGoroutinesDone = 0

func main() {
	for i := 0; i < 200; i++ {
		go worker()
	}

	time.Sleep(time.Hour)
}

func worker() {
	sendRequestWithSession()
	mutex.Lock()
	TotalGoroutinesDone++
	fmt.Println(TotalGoroutinesDone)
	mutex.Unlock()
}

func sendRequestWithSession() bool {
	session := azuretls.NewSession()
	defer session.Close()

	session.SetTimeout(25 * time.Second)
	session.UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
	err := session.ApplyJa3("771,4866-4867-4865-157-49313-49309-49233-156-49312-49308-49232-61-192-60-186-53-132-47-65-49196-49200-49327-49325-49188-49192-49162-49172-163-159-49315-49311-107-106-57-56-52394-49239-49235-162-158-49314-49310-49238-49234-196-195-103-64-190-189-136-135-51-50-69-68-52393-52392-49245-49249-49195-49199-49326-49324-49244-49248-49267-49271-49187-49191-49266-49270-49161-49171-255,0-11-10-35-22-23-13-43-45-51-21,29-23-1035-25-24,0-1-2", session.UserAgent)

	if err != nil {
		return false
	}

	if err := session.SetProxy("socks5://user:pass@host:port"); err != nil {
		return false
	}

	headers := azuretls.OrderedHeaders{
		{"Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"},
		{"Accept-Language", "ru-RU,ru;q=0.9"},
	}

	resp, err := session.Get("https://www.example.com", headers)

	if err != nil {
		return false
	}

	respText := string(resp.Body)

	return strings.Contains(respText, "")
}


```

Output from console:

First time
```
...
...
...
199
```

Second time
```
...
...
...
198
```

Third time
```
...
...
...
200
```

Only third time is good. (200 goroutines is done).

if i remove proxy from code it always last numbers is 200.
```
//if err := session.SetProxy("socks5://user:pass@host:port"); err != nil {
//		return false
//	}
```

First time
```
...
...
...
200
```

Second time
```
...
...
...
200
```

Third time
```
...
...
...
200
```

**Comment by Noooste** [comment]
Hello, sorry for this bug, it appeared in v1.2.7 but should be fixed in v1.2.8. Could you please confirm your version.

**Comment by byMonaco** [comment]
> Hello, sorry for this bug, it appeared in v1.2.7 but should be fixed in v1.2.8. Could you please confirm your version.

I am using 1.2.8 version

**Comment by Noooste** [comment]
I tested it myself and all 200 requests still work, but some of them (about 20) took a long time to process. After debugging, the last 20 are EOF which is not good, I will fix this problem as soon as possible.

**Comment by Noooste** [comment]
Also, use atomic when increment an integer

```go
package main

import (
	"fmt"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/Noooste/azuretls-client"
)

var mutex = &sync.Mutex{}
var nb = new(int64)

func main() {
	for i := 0; i < 200; i++ {
		go worker()
	}

	time.Sleep(time.Hour)
}

func worker() {
	sendRequestWithSession()
	mutex.Lock()
	r := atomic.AddInt64(nb, 1)
	fmt.Println(r)
	mutex.Unlock()
}

func sendRequestWithSession() bool {
	session := azuretls.NewSession()
	defer session.Close()

	session.SetTimeout(25 * time.Second)
	session.UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
	err := session.ApplyJa3("771,4866-4867-4865-157-49313-49309-49233-156-49312-49308-49232-61-192-60-186-53-132-47-65-49196-49200-49327-49325-49188-49192-49162-49172-163-159-49315-49311-107-106-57-56-52394-49239-49235-162-158-49314-49310-49238-49234-196-195-103-64-190-189-136-135-51-50-69-68-52393-52392-49245-49249-49195-49199-49326-49324-49244-49248-49267-49271-49187-49191-49266-49270-49161-49171-255,0-11-10-35-22-23-13-43-45-51-21,29-23-1035-25-24,0-1-2", session.UserAgent)

	if err != nil {
		return false
	}

	if err := session.SetProxy("socks5://user:pass@host:port"); err != nil {
		return false
	}

	headers := azuretls.OrderedHeaders{
		{"Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"},
		{"Accept-Language", "ru-RU,ru;q=0.9"},
	}

	resp, err := session.Get("https://www.google.com", headers)

	if err != nil {
		fmt.Println(err)
		return false
	}

	respText := string(resp.Body)

	return strings.Contains(respText, "")
}
```

**Comment by byMonaco** [comment]
> I tested it myself and all 200 requests still work, but some of them (about 20) took a long time to process. After debugging, the last 20 are EOF which is not good, I will fix this problem as soon as possible.

Thank you!

**Comment by byMonaco** [comment]
> After testing, it's a proxy problem. I've tested several proxies and some don't handle multiple connections well at the same time, while others do (maybe thread issues on their side). Unfortunately, there's nothing I can do about it.
> 
> For example, smartproxy doesn't have any problem about it where abcproxy does.

Thx for answer! 
Maybe you can add timeout. For example if GET request sending and no response within 60 seconds return new Error?

**Comment by Noooste** [comment]
This is already the case, I think your code didn't count right, because you didn't use atomic. I've tested several times, with good and bad proxies, both always respond with EOF or proxy timeout in the worst case. 

However, if you can see that it's really blocking the response indefinitely, then I'll check. Keep me posted!
