### ISSUE TITLE
content-type header

### ISSUE THREAD

**Issue by removeduser123** [Noooste/azuretls-client#37]
Content-type header is ignored when sending GET request

```
headers := azuretls.OrderedHeaders{
    {"content-type", "application/json"},
}

response, _ := session.Get("https://example.com", headers)
```

**Comment by Noooste** [comment]
Hello, 
You should not send the content type in a GET request, why send it without a payload?

**Comment by removeduser123** [comment]
Hello
In my case api returns 400 error code if I don't set this header

**Comment by Noooste** [comment]
Content length is suppressed to comply with RFC standards on this library, I will do a PR to override this.

**Comment by Noooste** [comment]
[v1.2.11](https://github.com/Noooste/azuretls-client/tree/v1.2.11) out
