### ISSUE TITLE
[BUG] azuretls session does not follow the set timeout for proxies

### ISSUE THREAD

**Issue by VegieIsCute** [Noooste/azuretls-client#41]
**Describe the bug**
When a timeout and proxy is set in an azuretls session, the request proceeds beyond the timeout.
It seems to be only accounting for the timeout **after** connecting to the proxy
The timeout should be the total time-limit for the **entire** request

**To Reproduce**
```
session := azuretls.NewSession()
	defer session.Close()
	session.SetTimeout(5 * time.Second)

	if err := session.SetProxy("http://YOUR_PROXY"); err != nil {
		fmt.Println("failed to set proxy")
		return
	}

	start := time.Now()
	response, err := session.Get("https://testfile.org/files-5GB")
	elapsed := time.Since(start)
	fmt.Println(elapsed.Seconds())

	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(response.StatusCode, string(response.Body), elapsed)
	}
```
(Set a proxy, preferably slow)

**Expected behavior**
To fail the entire request after the timeout has been reached.

**Screenshots**
![image](https://github.com/Noooste/azuretls-client/assets/49800712/a1ff7917-5515-43cb-94e2-c2558bb0bb61)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 120

**Comment by VegieIsCute** [comment]
The issue seems to be somewhat resolved, The request now fails if it passes the timeout which is good and expected. But an issue that still persists is shown below.

```
session := azuretls.NewSession()
	defer session.Close()
	session.SetTimeout(5 * time.Second)

	if err := session.SetProxy("http://geonode_15VNBesYw6:bcd07dcd-adbd-4f41-8fa0-3347aaddec8c@premium-residential.geonode.com:10027"); err != nil {
		fmt.Println("failed to set proxy")
		return
	}

	start := time.Now()
	response, err := session.Get("https://link.testfile.org/15MB")
	elapsed := time.Since(start)
	fmt.Println(elapsed.Seconds())

	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(response.StatusCode, string(response.Body), elapsed)
	}
```

When receiving a small response. everything seems normal, and the timeout works well. I noticed in the SetTimeout function is the code below

```
func (s *Session) SetTimeout(timeout time.Duration) {
	s.TimeOut = timeout
	if s.Transport != nil {
		s.Transport.TLSHandshakeTimeout = timeout
		s.Transport.ResponseHeaderTimeout = timeout
	}
}
```

The timeout for the session will be set to 5 seconds.
The timeout for the tls handshake will be set to 5 seconds.
The timeout for the response header timeout will be set to 5 seconds.

For the entire response, if tls handshake took 4 seconds, then repsonse header was also 4 seconds the total request time would probably be around 8 seconds. which exceeds our 5 second session timeout and the request will fail, which is good and expected, however the request continues to run for the entirety of the time allowed. Many http libraries across multiple languages and frameworks stop the request immediately as the timeout is hit, which stops blocking the thread. however azuretls continues to block the thread until the maximum allowed time is hit and then the request fails for timeout.

The above code provided for me took a time of 11.8346901 seconds before timing out, the goroutine was blocked for that time, when it should have only been blocked for 5 seconds.

**Comment by Noooste** [comment]
Indeed, but I should have corrected this issue on the v1.2.15, you still facing this issue on this version ?

**Comment by VegieIsCute** [comment]
You did correct it for the most part. Requests that finish after the timeout no longer count as successful. But the requests if they take long enough still block the thread for the full time allowed.

Before a timeout set to 5 seconds would finish at 6.7seconds and count as successful. This is because the proxy connection took like 4 seconds and the response took like 2-3 seconds.

Now the request takes 6.7seconds but instead of counting as successful, it now counts as failed which is good. But like i told you, the thread shouldn't be blocked for 6.7 seconds if the timeout is 5 seconds. It should be blocked for 5 seconds, if the request finishes before it, it should count as a success, at 5 seconds if it still hasn't finished, the request should be canceled/ended and should be counted as failed

**Comment by VegieIsCute** [comment]
I noticed in test/session_test.go under timeout test, the timeout is set to 1 second. When it's set to 1 second the request does end on time. This is because the timeout time is so small that the proxy connection probably times out before proceeding which gives the illusion of a fixed bug. Try to set the timeout to 5 seconds and try to download the 5gb file. The timeout will probably be far greater than 5 seconds

**Comment by VegieIsCute** [comment]
My fault, I meant to say the go routine was blocked, not that the goroutine was blocking the thread. This is because in my code, the function creates multiple requests, then calls a callback after the request was finished.

```go
callback := func(c string) { fmt.Println(c) }
	go func() {
		session := azuretls.NewSession()
		defer session.Close()

		session.SetTimeout(5 * time.Second)

		if err := session.SetProxy("http://YOUR_PROXY"); err != nil {
			fmt.Println("failed to set proxy")
			return
		}

		start := time.Now()
		_, err := session.Get("https://link.testfile.org/15MB")
		elapsed := time.Since(start)

		callback(fmt.Sprintf("the goroutine was blocked for %.2f seconds", elapsed.Seconds()))

		if err != nil {
			callback("error")
		} else {
			callback("success")
		}
	}()

	time.Sleep(time.Hour)
```
The output of the above code in my case was:
the goroutine was blocked for 10.03 seconds
error

As you are most likely aware that applications with UI/UX have a main event loop and other functions run on separate threads. This is why it is important for my application, since callbacks need to be called on time by canceling the request after the set timeout. Every other http library across any language does this. There is indeed a purpose to it.

**Comment by Noooste** [comment]
Thanks for sharing, I have fixed this issue in a PR

**Comment by Noooste** [comment]
Alright, thanks I will see what's wrong and fix it 👍
