### ISSUE TITLE
[BUG] TLS connection does not use the set user agent

### ISSUE THREAD

**Issue by VegieIsCute** [Noooste/azuretls-client#46]
**Describe the bug**
When the TLS handshake request is sent, the set user agent is not present, and the default Go agent is being used.

**To Reproduce**
```go
session := azuretls.NewSession()
	defer session.Close()

	session.UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0"
	session.InsecureSkipVerify = true

	//http://127.0.0.1:8866 is the default address used by fiddler everywhere
	if err := session.SetProxy("http://127.0.0.1:8866"); err != nil {
		fmt.Println("failed to set proxy")
		return
	}

	response, err := session.Get("https://google.com")

	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(response.StatusCode, string(response.Body))
	}
```

**Expected behavior**
The request should use the set user agent, maybe keep-alive would be a nice touch but it isn't required.

**Screenshots**
azuretls after headers are set:
![image](https://github.com/Noooste/azuretls-client/assets/49800712/ba18b326-7a13-4c83-b7b8-902e1b59c8c6)

firefox:
![image](https://github.com/Noooste/azuretls-client/assets/49800712/4a687098-abb7-499b-bfbf-45548dd0a1b1)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 124

**Additional information:**
The program I'm using to inspect the web traffic is Fiddler Everywhere which comes with a 10-day free trial.
https://www.telerik.com/download/fiddler-everywhere

**Comment by Noooste** [comment]
Thanks for this, it will be patched.
