### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by venom-AIO** [Noooste/azuretls-client#50]
When trying to install the package, I am unable to do so because of this error:
![Capture](https://github.com/Noooste/azuretls-client/assets/90580643/1a237a5c-8c35-4203-93cd-183c06c95e5b)

"go\src\github.com\Noooste\azuretls-client\websocket.go:66:18: cannot use s.CookieJar (variable of type *cookiejar.Jar) as "net/http".CookieJar value in assignment: *cookiejar.Jar does not implement "net/http".CookieJar (wrong type for method Cookies)
                have Cookies(*url.URL) ([]*"github.com/Noooste/fhttp".Cookie)
                want Cookies(*url.URL) []*"net/http".Cookie
go\src\github.com\Noooste\azuretls-client\websocket.go:90:72: too many arguments in call to ws.dialer.DialContext
        have (context.Context, string, "github.com/Noooste/fhttp".Header, []string)
        want (context.Context, string, "net/http".Header)
go\src\github.com\Noooste\azuretls-client\websocket.go:101:13: cannot use resp (variable of type *"net/http".Response) as *"github.com/Noooste/fhttp".Response value in struct literal"

 - OS: Windows

**Comment by Noooste** [comment]
Hello, try `go get github.com/Noooste/azuretls-client@latest`

**Comment by venom-AIO** [comment]
> Hello, try `go get github.com/Noooste/azuretls-client@latest`

This worked, thank you!
