### ISSUE TITLE
Wrong Chrome extensions

### ISSUE THREAD

**Issue by elpaxel** [Noooste/azuretls-client#51]
azuretls-client:

    {
      "name": "supported_versions (43)",
      "versions": [
        "TLS 1.3",
        "TLS 1.2",
        "TLS 1.1"
      ]
    }

real chrome:

    {
      "name": "supported_versions (43)",
      "versions": [
        "TLS_GREASE (0x1a1a)",
        "TLS 1.3",
        "TLS 1.2"
      ]
    }

I thinks that is because [this](https://github.com/Noooste/azuretls-client/blob/8621d88bc39d8c094e24806610945618b98dd3ec/ja3.go#L364) never runs.

Also chrome now has:

    {
      "name": "TLS_GREASE (0x9a9a)"
    }

at the last index too (not only first index).

**Comment by Noooste** [comment]
Hello, thank you for reporting this problem, it is related to JA3 parsing and will be corrected. If you want to use the latest Chrome fingerprint, azuretls implements it by default when creating a new session.
