### ISSUE TITLE
(somewhat) Wrong Chrome/Firefox extensions

### ISSUE THREAD

**Issue by elpaxel** [Noooste/azuretls-client#53]
Thank you for the fast reaction on the last issue. This time I observed 2 more inconsistencies.

1. In the last PR you added TLS_GREASE second to last in Chrome JA3. But the real Chrome adds TLS_GREASE last on the first connect (incognito window) and second to last on subsequent requests.

2. Firefox has 3 extensions that differs.

azuretls-client:

    {
      "name": "delegated_credentials (34)",
      "signature_hash_algorithms": [
        "ecdsa_secp256r1_sha256",
        "ecdsa_secp384r1_sha384",
        "ecdsa_secp521r1_sha512"
      ]
    },
    {
      "name": "signature_algorithms (13)",
      "signature_algorithms": [
        "ecdsa_secp256r1_sha256",
        "rsa_pss_rsae_sha256",
        "rsa_pkcs1_sha256",
        "ecdsa_secp384r1_sha384",
        "rsa_pss_rsae_sha384",
        "rsa_pkcs1_sha384",
        "rsa_pss_rsae_sha512",
        "rsa_pkcs1_sha512"
      ]
    },
    {
      "name": "record_size_limit (28)",
      "data": "0000"
    }

Real Firefox:

    {
      "name": "delegated_credentials (34)",
      "signature_hash_algorithms": [
        "ecdsa_secp256r1_sha256",
        "ecdsa_secp384r1_sha384",
        "ecdsa_secp521r1_sha512",
        "ecdsa_sha1"
      ]
    },
    {
      "name": "signature_algorithms (13)",
      "signature_algorithms": [
        "ecdsa_secp256r1_sha256",
        "ecdsa_secp384r1_sha384",
        "ecdsa_secp521r1_sha512",
        "rsa_pss_rsae_sha256",
        "rsa_pss_rsae_sha384",
        "rsa_pss_rsae_sha512",
        "rsa_pkcs1_sha256",
        "rsa_pkcs1_sha384",
        "rsa_pkcs1_sha512",
        "ecdsa_sha1",
        "rsa_pkcs1_sha1"
      ]
    },
    {
      "name": "record_size_limit (28)",
      "data": "4001"
    }

**Comment by Noooste** [comment]
For the former, incognito mode has no impact on the JA3 footprint. What causes GREASE to be in the last index or before padding is that padding is only added if the total length of the hello client payload is less than 512 bytes, see [rfc7685](https://datatracker.ietf.org/doc/html/rfc7685#section-1).

For Firefox, I will make a fix in the next PR. If in the future this changes, I will make the corresponding fix but remember that you can assign your own Client Hello by assigning to `azuretls.GetClientHelloSpec` your own implementation (you have some examples in [profiles.go](https://github.com/Noooste/azuretls-client/blob/main/profiles.go)).
