### ISSUE TITLE
[Feature request] Ability to add websocket extensions

### ISSUE THREAD

**Issue by VegieIsCute** [Noooste/azuretls-client#57]
![image](https://github.com/Noooste/azuretls-client/assets/49800712/e3d6b8b9-1288-423c-bf46-4b7177099541)
![image](https://github.com/Noooste/azuretls-client/assets/49800712/ea105753-83cb-410a-be9c-f7193048d7ca)

Although the client doesn't have to manually support extensions show in the images, it would be good to be able to modify them. The handling of the extensions can be done in the callback itself

**Comment by Noooste** [comment]
This is because the library I'm using (a fork of https://github.com/gorilla/websocket) supports no websocket extensions other than `server_no_context_takeover` and `client_no_context_takeover`. I will try to implement then since it's part of the [RFC](https://datatracker.ietf.org/doc/html/rfc7692#section-7.1)

**Comment by VegieIsCute** [comment]
Any update on this? When receiving large payloads from WebSocket connections, the server opts to use compression which causes the following error: 
![image](https://github.com/Noooste/azuretls-client/assets/49800712/c463003f-0e83-4bdf-b8ba-ea313c52c2bb)

This occurs on ReadMessage.
With further research this issue is related to the missing permessage-deflate feature in Sec-Websocket-Extensions.

**Comment by Noooste** [comment]
I didn't fix this problem because I couldn't figure out how to set `client_max_window_bits`. I'll make the change to enable compression though, the only extensions supported at the moment are `server_no_context_takeover` and `client_no_context_takeover`.

**Comment by VegieIsCute** [comment]
Could you add the ability to at least add it to the header?, functionality isn't needed.

**Comment by Noooste** [comment]
No, because they won't be handled correctly, but you can fork the https://github.com/Noooste/websocket package and this package to suit your needs.
