### ISSUE TITLE
Wrong Chrome extensions (again)

### ISSUE THREAD

**Issue by elpaxel** [Noooste/azuretls-client#58]
Let me say first that I'm really sorry.

azuretls-client:

    "extensions": [
      {
        "name": "TLS_GREASE (0xaaaa)"
      },
      {
        "name": "ec_point_formats (11)",
        "elliptic_curves_point_formats": [
          "0x00"
        ]
      },
      {
        "name": "server_name (0)",
        "server_name": "tls.peet.ws"
      },
      {
        "name": "signed_certificate_timestamp (18)"
      },
      {
        "name": "application_layer_protocol_negotiation (16)",
        "protocols": [
          "h2",
          "http/1.1"
        ]
      },
      {
        "name": "psk_key_exchange_modes (45)",
        "PSK_Key_Exchange_Mode": "PSK with (EC)DHE key establishment (psk_dhe_ke) (1)"
      },
      {
        "name": "extensionRenegotiationInfo (boringssl) (65281)",
        "data": "00"
      },
      {
        "name": "application_settings (17513)",
        "protocols": [
          "h2"
        ]
      },
      {
        "name": "supported_groups (10)",
        "supported_groups": [
          "TLS_GREASE (0xbaba)",
          "X25519 (29)",
          "P-256 (23)",
          "P-384 (24)"
        ]
      },
      {
        "name": "extended_master_secret (23)",
        "master_secret_data": "",
        "extended_master_secret_data": ""
      },
      {
        "name": "key_share (51)",
        "shared_keys": [
          {
            "TLS_GREASE (0xbaba)": "00"
          },
          {
            "X25519 (29)": "sensitive"
          }
        ]
      },
      {
        "name": "compress_certificate (27)",
        "algorithms": [
          "brotli (2)"
        ]
      },
      {
        "name": "signature_algorithms (13)",
        "signature_algorithms": [
          "ecdsa_secp256r1_sha256",
          "rsa_pss_rsae_sha256",
          "rsa_pkcs1_sha256",
          "ecdsa_secp384r1_sha384",
          "rsa_pss_rsae_sha384",
          "rsa_pkcs1_sha384",
          "rsa_pss_rsae_sha512",
          "rsa_pkcs1_sha512"
        ]
      },
      {
        "name": "session_ticket (35)",
        "data": ""
      },
      {
        "name": "extensionEncryptedClientHello (boringssl) (65037)",
        "data": "sensitive"
      },
      {
        "name": "supported_versions (43)",
        "versions": [
          "TLS 1.3",
          "TLS 1.2"
        ]
      },
      {
        "name": "status_request (5)",
        "status_request": {
          "certificate_status_type": "OSCP (1)",
          "responder_id_list_length": 0,
          "request_extensions_length": 0
        }
      }
    ]

real chrome:

    "extensions": [
      {
        "name": "TLS_GREASE (0x0a0a)"
      },
      {
        "name": "ec_point_formats (11)",
        "elliptic_curves_point_formats": [
          "0x00"
        ]
      },
      {
        "name": "server_name (0)",
        "server_name": "tls.peet.ws"
      },
      {
        "name": "signed_certificate_timestamp (18)"
      },
      {
        "name": "application_layer_protocol_negotiation (16)",
        "protocols": [
          "h2",
          "http/1.1"
        ]
      },
      {
        "name": "psk_key_exchange_modes (45)",
        "PSK_Key_Exchange_Mode": "PSK with (EC)DHE key establishment (psk_dhe_ke) (1)"
      },
      {
        "name": "extensionRenegotiationInfo (boringssl) (65281)",
        "data": "00"
      },
      {
        "name": "application_settings (17513)",
        "protocols": [
          "h2"
        ]
      },
      {
        "name": "supported_groups (10)",
        "supported_groups": [
          "TLS_GREASE (0x2a2a)",
          "X25519 (29)",
          "P-256 (23)",
          "P-384 (24)"
        ]
      },
      {
        "name": "extended_master_secret (23)",
        "master_secret_data": "",
        "extended_master_secret_data": ""
      },
      {
        "name": "key_share (51)",
        "shared_keys": [
          {
            "TLS_GREASE (0x2a2a)": "00"
          },
          {
            "X25519 (29)": "sensitive"
          }
        ]
      },
      {
        "name": "compress_certificate (27)",
        "algorithms": [
          "brotli (2)"
        ]
      },
      {
        "name": "signature_algorithms (13)",
        "signature_algorithms": [
          "ecdsa_secp256r1_sha256",
          "rsa_pss_rsae_sha256",
          "rsa_pkcs1_sha256",
          "ecdsa_secp384r1_sha384",
          "rsa_pss_rsae_sha384",
          "rsa_pkcs1_sha384",
          "rsa_pss_rsae_sha512",
          "rsa_pkcs1_sha512"
        ]
      },
      {
        "name": "session_ticket (35)",
        "data": ""
      },
      {
        "name": "extensionEncryptedClientHello (boringssl) (65037)",
        "data": "sensitive"
      },
      {
        "name": "supported_versions (43)",
        "versions": [
          "TLS_GREASE (0xbaba)",
          "TLS 1.3",
          "TLS 1.2"
        ]
      },
      {
        "name": "status_request (5)",
        "status_request": {
          "certificate_status_type": "OSCP (1)",
          "responder_id_list_length": 0,
          "request_extensions_length": 0
        }
      },
      {
        "name": "TLS_GREASE (0xaaaa)"
      }
    ]

for the tests:

    {
      "ja3": "771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,11-0-18-16-45-65281-17513-10-23-51-27-13-35-65037-43-5,29-23-24,0",
      "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"
    }

So "supported_versions" lost its grease since last pr.
Also real chrome adds grease at the end and there is no padding. Last time you said grease added before padding because of the hello client payload length. But when there is no padding azuretls-client doesn't add grease alltogether. So if I'm just don't understand the subject then nevermind.

P.S. Without using ApplyJa3 the last grease and padding are placed correctly.

**Comment by elpaxel** [comment]
It should be like this (code is not tested):

    if navigator == Chrome {
        lastIndex := len(extensions) - 1
        last := extensions[lastIndex]
        
        switch last.(type) {
            case tls.UtlsPaddingExtension: // also "pre_shared_key (41)" but there is none in the library as I see
                extensions[lastIndex] = &tls.UtlsGREASEExtension{}
                extensions = append(extensions, last)
            default:
                extensions = append(extensions, &tls.UtlsGREASEExtension{})
        }
    }

Chrome adds TLS_GREASE at the end except when there is "pre_shared_key (41)" or "padding (21)".

**Comment by Noooste** [comment]
You should not include `pre_shared_key (41)` in the ja3 fingerprint since it's a new TLS connection

**Comment by elpaxel** [comment]
Yep I don't use it. I just wrote about it for the info.

**Comment by elpaxel** [comment]
I'm really sorry again. But I don't know if you understood correctly. It is really should be like in the code I'm mentioned.
Chrome always adds TLS_GREASE at the end except when there is UtlsPaddingExtension then TLS_GREASE is second to last.
