### ISSUE TITLE
[BUG] Callback enhancements follow up

### ISSUE THREAD

**Issue by VegieIsCute** [Noooste/azuretls-client#64]
https://github.com/Noooste/azuretls-client/issues/62#issue-2190483494

Following up from this bug, the context is not set in the azuretls.Context object before calling the callback. This results in a nil context error.
![image](https://github.com/Noooste/azuretls-client/assets/49800712/8cd6c784-35b1-4e30-bbaa-684543cb50b3)

![image](https://github.com/Noooste/azuretls-client/assets/49800712/cc98c03d-470a-47c7-8e18-9894e523b434)

Seems like a simple mistake its just a one line fix.

Also another issue, the Err object in the context is still ignored. This is caused by variable reassignment later on.
![image](https://github.com/Noooste/azuretls-client/assets/49800712/f4a626e6-8d99-4cfe-819d-b47a62f5487b)

**Comment by Noooste** [comment]
I don't understand the second issue, I have tested on my side and it's working, could you provide me an example ?
