### ISSUE TITLE
[BUG] invalid context is returned

### ISSUE THREAD

**Issue by VegieIsCute** [Noooste/azuretls-client#72]
**Describe the bug**
When context is retrieved from a callback, the provided context is invalid.

**To Reproduce**
```go
exampleContext, _ := context.WithCancel(context.Background())
	session := azuretls.NewSessionWithContext(exampleContext)

	session.CallbackWithContext = func(ctx *azuretls.Context) {
		exampleContextFromCtx := ctx.Context()
		if exampleContextFromCtx == exampleContext {
			fmt.Println("match")
		} else {
			fmt.Println("no match")
			session1 := azuretls.NewSessionWithContext(exampleContextFromCtx)
			_, err := session1.Get("https://httpbin.org/headers")

			if err != nil {
				log.Fatal(err)
			}
		}
	}

	_, _ = session.Get("https://httpbin.org/headers")
```

**Expected behavior**
The request inside the callback should work, but errors with a "canceled" message, even though context wasn't canceled. This is because an invalid context is being returned.

**Screenshots**
![image](https://github.com/Noooste/azuretls-client/assets/49800712/5c3bf198-7f27-460d-8947-e231a712f363)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 123

**Comment by Noooste** [comment]
It's patched [v1.4.8](https://github.com/Noooste/azuretls-client/releases/tag/v1.4.8)
