### ISSUE TITLE
unexpected EOF

### ISSUE THREAD

**Issue by byMonaco** [Noooste/azuretls-client#74]
if response redirect location is not http url => error unexpected EOF

from example:
Location header from server is http://127.0.0.1:80/login => OK
Location header from server is ms-xal-000000004c12ae6f://auth/?code=M.C504_BL2.2.U.33333333-4444-2222-4444-123123123&state=r8z8%2bUc8/tOLmhO9agsdt43gawwfLONoY%2bRUXPpjQzdirT6XK32gadfhahUJTvbe79OOeZckPdtrQGdvLuJ4ppPIHagasdfasdfadfAc%3d => unexpected EOF

if i set "session.MaxRedirects = 0" => unexpected EOF

P.S. Works good if use session.Do with DisableRedirects: true param.

**Comment by Noooste** [comment]
Hello, yes you have to use `DisableRedirects` for this
