### ISSUE TITLE
proxy connection timeout

### ISSUE THREAD

**Issue by byMonaco** [Noooste/azuretls-client#95]
After did many requests in multi-threads, it show proxy connection timeout, and after 20 sec its continue to work. I checked with differents proxies. 
If i using 300 threads it doing 1000-1100 success connections and after that return error: proxy connection timeout => waiting 15 seconds (Its session timeouts) and continue working. And again stops on 2100-2300 success connections.

![image](https://github.com/Noooste/azuretls-client/assets/60541017/94b9cc54-8768-4e8f-a4d5-e96a2888800c)

Maybe defer session.Close() don't close the proxy connection? And proxy connection don't closed after Close the session?

**Comment by Noooste** [comment]
Hello,
Could be proxy related, please use different proxy providers to check.

**Comment by byMonaco** [comment]
Close it pls. Reason is my internet provider block traffic if i do 100+ threads.
