### ISSUE TITLE
Ipv6 proxy

### ISSUE THREAD

**Issue by byMonaco** [Noooste/azuretls-client#98]
Can you add support of ipv6 proxy?

Thank you!

**Comment by Noooste** [comment]
Hello,
Ipv6 proxies aren't supported yet

**Comment by TheRealStingo** [comment]
> Hello, Ipv6 is not used enough to implement it, i will check what i can do

I think its a needed feature nowaday , especially that most services now offer and accept connections from IPV6

**Comment by Noooste** [comment]
Do you have any cheap proxies provider to check this feature?

**Comment by TheRealStingo** [comment]
> Do you have any cheap proxies provider to check this feature?

Please DM on discord , I ll provide you with some @therealstingo

**Comment by Noooste** [comment]
So I've checked on my own with a few IPV6 providers, and it works.
Do you need the client to also accept proxies in IPV6 format or something else? 
Please specify your requirements, I'll do my best to meet them.

**Comment by byMonaco** [comment]
> So I've checked on my own with a few IPV6 providers, and it works.
> Do you need the client to also accept proxies in IPV6 format or something else?
> Please specify your requirements, I'll do my best to meet them.

Hello, yes. Will be good if I can set ipv6 proxy to session

**Comment by Noooste** [comment]
Alright, I'll implement this 👍

**Comment by Noooste** [comment]
Did you try to directly format your proxy correctly: `http://user:pass@[2001:0db8:85a3:0000:0000:8a2e:0370:7334]:8080`

**Comment by Noooste** [comment]
> Did you try to directly format your proxy correctly: `http://user:pass@[2001:0db8:85a3:0000:0000:8a2e:0370:7334]:8080`

Since this works well and analyzing an IPV6 proxy to format it properly would be complicated, I'll set this issue as solved.
