### ISSUE TITLE
[BUG] Bad side effects causing "use of closed network connection" error on consecutive requests as a result of #80

### ISSUE THREAD

**Issue by stack1ng** [Noooste/azuretls-client#99]
**Describe the bug**
When InsecureSkipVerify is set to true on a Session instance, Consecutive requests to the same host will return a "write tcp 192.168.1.22:60159->216.239.38.120:443: use of closed network connection" error.

**To Reproduce**
The following code is a minimal reproduction of the error:
```
package main

import (
	"fmt"

	"github.com/Noooste/azuretls-client"
)

func main() {
	session := azuretls.NewSession()

	// commenting out this line will make the code work
	session.InsecureSkipVerify = true

	response, err := session.Get("https://www.google.com")
	if err != nil {
		panic(err)
	}
	fmt.Println(response.StatusCode)
	response, err = session.Get("https://www.google.com")
	if err != nil {
		panic(err)
	}
	fmt.Println(response.StatusCode)
}
```

**Expected behavior**
I expected the TLS session to be correctly reused, but it seems something is causing the underlying TCP connection to close.

**Tested on:**
go version go1.22.2 windows/amd64
go version go1.22.4 darwin/arm64

**Additional context**
I ivestigated a bit myself and found that the [Conn.checkTLS and Conn.isActive](https://github.com/Noooste/azuretls-client/blob/main/connection.go#L179) functions are causing it, after the changes made in #80. 

In that PR, the [Conn.isActive function was created](https://github.com/Noooste/azuretls-client/pull/80/commits/deb8115f87d5bcbaefa3307ead4b6ea8afc3e2b8#diff-25a7cf08cc8fc8eb57475835cc380524de2fd1215cda9c6915132ae86dbd80a7R202) which has a side effect of closing the connection that it is attempting to check (on the environments I tested with). Conn.isActive is only called from Conn.checkTLS [here](https://github.com/Noooste/azuretls-client/blob/main/connection.go#L192) if c.TLS.ConnectionState().VerifiedChains is nil, which is true when InsecureSkipVerify is true.

So from what I can tell, #80 just makes InsecureSkipVerify close TCP connections ungracefully after each request and that happened to resolve the issue with consecutive requests hanging described in #76. Even running the error reproduction code in the issue prints the error im describing. I am not sure what to do about the original issue (#76) but the changes made clearly broke more things than they fixed and should be rolled back.

**Comment by byMonaco** [comment]
I have the same error
